// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NewsManagementProto.proto

package com.example.NewsManagement.proto;

public interface CommentDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.NewsManagement.proto.CommentDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string text = 2;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 2;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <code>.com.example.NewsManagement.proto.UserAccountDTO userAccount = 3;</code>
   * @return Whether the userAccount field is set.
   */
  boolean hasUserAccount();
  /**
   * <code>.com.example.NewsManagement.proto.UserAccountDTO userAccount = 3;</code>
   * @return The userAccount.
   */
  com.example.NewsManagement.proto.UserAccountDTO getUserAccount();
  /**
   * <code>.com.example.NewsManagement.proto.UserAccountDTO userAccount = 3;</code>
   */
  com.example.NewsManagement.proto.UserAccountDTOOrBuilder getUserAccountOrBuilder();

  /**
   * <code>.com.example.NewsManagement.proto.NewsDTO news = 4;</code>
   * @return Whether the news field is set.
   */
  boolean hasNews();
  /**
   * <code>.com.example.NewsManagement.proto.NewsDTO news = 4;</code>
   * @return The news.
   */
  com.example.NewsManagement.proto.NewsDTO getNews();
  /**
   * <code>.com.example.NewsManagement.proto.NewsDTO news = 4;</code>
   */
  com.example.NewsManagement.proto.NewsDTOOrBuilder getNewsOrBuilder();
}
