// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NewsManagementProto.proto

package com.example.NewsManagement.proto;

/**
 * Protobuf type {@code com.example.NewsManagement.proto.NewsDTO}
 */
public final class NewsDTO extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.NewsManagement.proto.NewsDTO)
    NewsDTOOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NewsDTO.newBuilder() to construct.
  private NewsDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NewsDTO() {
    username_ = "";
    password_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new NewsDTO();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NewsDTO(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            username_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            password_ = s;
            break;
          }
          case 34: {
            com.example.NewsManagement.proto.UserAccountDTO.Builder subBuilder = null;
            if (userAccount_ != null) {
              subBuilder = userAccount_.toBuilder();
            }
            userAccount_ = input.readMessage(com.example.NewsManagement.proto.UserAccountDTO.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(userAccount_);
              userAccount_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.NewsManagement.proto.NewsManagementProto.internal_static_com_example_NewsManagement_proto_NewsDTO_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.NewsManagement.proto.NewsManagementProto.internal_static_com_example_NewsManagement_proto_NewsDTO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.NewsManagement.proto.NewsDTO.class, com.example.NewsManagement.proto.NewsDTO.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int USERNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object username_;
  /**
   * <code>string username = 2;</code>
   * @return The username.
   */
  @java.lang.Override
  public java.lang.String getUsername() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      username_ = s;
      return s;
    }
  }
  /**
   * <code>string username = 2;</code>
   * @return The bytes for username.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      username_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PASSWORD_FIELD_NUMBER = 3;
  private volatile java.lang.Object password_;
  /**
   * <code>string password = 3;</code>
   * @return The password.
   */
  @java.lang.Override
  public java.lang.String getPassword() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      password_ = s;
      return s;
    }
  }
  /**
   * <code>string password = 3;</code>
   * @return The bytes for password.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPasswordBytes() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      password_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERACCOUNT_FIELD_NUMBER = 4;
  private com.example.NewsManagement.proto.UserAccountDTO userAccount_;
  /**
   * <code>.com.example.NewsManagement.proto.UserAccountDTO userAccount = 4;</code>
   * @return Whether the userAccount field is set.
   */
  @java.lang.Override
  public boolean hasUserAccount() {
    return userAccount_ != null;
  }
  /**
   * <code>.com.example.NewsManagement.proto.UserAccountDTO userAccount = 4;</code>
   * @return The userAccount.
   */
  @java.lang.Override
  public com.example.NewsManagement.proto.UserAccountDTO getUserAccount() {
    return userAccount_ == null ? com.example.NewsManagement.proto.UserAccountDTO.getDefaultInstance() : userAccount_;
  }
  /**
   * <code>.com.example.NewsManagement.proto.UserAccountDTO userAccount = 4;</code>
   */
  @java.lang.Override
  public com.example.NewsManagement.proto.UserAccountDTOOrBuilder getUserAccountOrBuilder() {
    return getUserAccount();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!getUsernameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, username_);
    }
    if (!getPasswordBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, password_);
    }
    if (userAccount_ != null) {
      output.writeMessage(4, getUserAccount());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!getUsernameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, username_);
    }
    if (!getPasswordBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, password_);
    }
    if (userAccount_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getUserAccount());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.NewsManagement.proto.NewsDTO)) {
      return super.equals(obj);
    }
    com.example.NewsManagement.proto.NewsDTO other = (com.example.NewsManagement.proto.NewsDTO) obj;

    if (getId()
        != other.getId()) return false;
    if (!getUsername()
        .equals(other.getUsername())) return false;
    if (!getPassword()
        .equals(other.getPassword())) return false;
    if (hasUserAccount() != other.hasUserAccount()) return false;
    if (hasUserAccount()) {
      if (!getUserAccount()
          .equals(other.getUserAccount())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUsername().hashCode();
    hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
    hash = (53 * hash) + getPassword().hashCode();
    if (hasUserAccount()) {
      hash = (37 * hash) + USERACCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getUserAccount().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.NewsManagement.proto.NewsDTO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.NewsManagement.proto.NewsDTO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.NewsManagement.proto.NewsDTO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.NewsManagement.proto.NewsDTO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.NewsManagement.proto.NewsDTO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.NewsManagement.proto.NewsDTO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.NewsManagement.proto.NewsDTO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.NewsManagement.proto.NewsDTO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.NewsManagement.proto.NewsDTO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.NewsManagement.proto.NewsDTO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.NewsManagement.proto.NewsDTO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.NewsManagement.proto.NewsDTO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.NewsManagement.proto.NewsDTO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.NewsManagement.proto.NewsDTO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.NewsManagement.proto.NewsDTO)
      com.example.NewsManagement.proto.NewsDTOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.NewsManagement.proto.NewsManagementProto.internal_static_com_example_NewsManagement_proto_NewsDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.NewsManagement.proto.NewsManagementProto.internal_static_com_example_NewsManagement_proto_NewsDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.NewsManagement.proto.NewsDTO.class, com.example.NewsManagement.proto.NewsDTO.Builder.class);
    }

    // Construct using com.example.NewsManagement.proto.NewsDTO.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      username_ = "";

      password_ = "";

      if (userAccountBuilder_ == null) {
        userAccount_ = null;
      } else {
        userAccount_ = null;
        userAccountBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.NewsManagement.proto.NewsManagementProto.internal_static_com_example_NewsManagement_proto_NewsDTO_descriptor;
    }

    @java.lang.Override
    public com.example.NewsManagement.proto.NewsDTO getDefaultInstanceForType() {
      return com.example.NewsManagement.proto.NewsDTO.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.NewsManagement.proto.NewsDTO build() {
      com.example.NewsManagement.proto.NewsDTO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.NewsManagement.proto.NewsDTO buildPartial() {
      com.example.NewsManagement.proto.NewsDTO result = new com.example.NewsManagement.proto.NewsDTO(this);
      result.id_ = id_;
      result.username_ = username_;
      result.password_ = password_;
      if (userAccountBuilder_ == null) {
        result.userAccount_ = userAccount_;
      } else {
        result.userAccount_ = userAccountBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.NewsManagement.proto.NewsDTO) {
        return mergeFrom((com.example.NewsManagement.proto.NewsDTO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.NewsManagement.proto.NewsDTO other) {
      if (other == com.example.NewsManagement.proto.NewsDTO.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getUsername().isEmpty()) {
        username_ = other.username_;
        onChanged();
      }
      if (!other.getPassword().isEmpty()) {
        password_ = other.password_;
        onChanged();
      }
      if (other.hasUserAccount()) {
        mergeUserAccount(other.getUserAccount());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.NewsManagement.proto.NewsDTO parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.NewsManagement.proto.NewsDTO) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object username_ = "";
    /**
     * <code>string username = 2;</code>
     * @return The username.
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string username = 2;</code>
     * @return The bytes for username.
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string username = 2;</code>
     * @param value The username to set.
     * @return This builder for chaining.
     */
    public Builder setUsername(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      username_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string username = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsername() {
      
      username_ = getDefaultInstance().getUsername();
      onChanged();
      return this;
    }
    /**
     * <code>string username = 2;</code>
     * @param value The bytes for username to set.
     * @return This builder for chaining.
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      username_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object password_ = "";
    /**
     * <code>string password = 3;</code>
     * @return The password.
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string password = 3;</code>
     * @return The bytes for password.
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string password = 3;</code>
     * @param value The password to set.
     * @return This builder for chaining.
     */
    public Builder setPassword(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      password_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string password = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPassword() {
      
      password_ = getDefaultInstance().getPassword();
      onChanged();
      return this;
    }
    /**
     * <code>string password = 3;</code>
     * @param value The bytes for password to set.
     * @return This builder for chaining.
     */
    public Builder setPasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      password_ = value;
      onChanged();
      return this;
    }

    private com.example.NewsManagement.proto.UserAccountDTO userAccount_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.NewsManagement.proto.UserAccountDTO, com.example.NewsManagement.proto.UserAccountDTO.Builder, com.example.NewsManagement.proto.UserAccountDTOOrBuilder> userAccountBuilder_;
    /**
     * <code>.com.example.NewsManagement.proto.UserAccountDTO userAccount = 4;</code>
     * @return Whether the userAccount field is set.
     */
    public boolean hasUserAccount() {
      return userAccountBuilder_ != null || userAccount_ != null;
    }
    /**
     * <code>.com.example.NewsManagement.proto.UserAccountDTO userAccount = 4;</code>
     * @return The userAccount.
     */
    public com.example.NewsManagement.proto.UserAccountDTO getUserAccount() {
      if (userAccountBuilder_ == null) {
        return userAccount_ == null ? com.example.NewsManagement.proto.UserAccountDTO.getDefaultInstance() : userAccount_;
      } else {
        return userAccountBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.example.NewsManagement.proto.UserAccountDTO userAccount = 4;</code>
     */
    public Builder setUserAccount(com.example.NewsManagement.proto.UserAccountDTO value) {
      if (userAccountBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        userAccount_ = value;
        onChanged();
      } else {
        userAccountBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.example.NewsManagement.proto.UserAccountDTO userAccount = 4;</code>
     */
    public Builder setUserAccount(
        com.example.NewsManagement.proto.UserAccountDTO.Builder builderForValue) {
      if (userAccountBuilder_ == null) {
        userAccount_ = builderForValue.build();
        onChanged();
      } else {
        userAccountBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.example.NewsManagement.proto.UserAccountDTO userAccount = 4;</code>
     */
    public Builder mergeUserAccount(com.example.NewsManagement.proto.UserAccountDTO value) {
      if (userAccountBuilder_ == null) {
        if (userAccount_ != null) {
          userAccount_ =
            com.example.NewsManagement.proto.UserAccountDTO.newBuilder(userAccount_).mergeFrom(value).buildPartial();
        } else {
          userAccount_ = value;
        }
        onChanged();
      } else {
        userAccountBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.example.NewsManagement.proto.UserAccountDTO userAccount = 4;</code>
     */
    public Builder clearUserAccount() {
      if (userAccountBuilder_ == null) {
        userAccount_ = null;
        onChanged();
      } else {
        userAccount_ = null;
        userAccountBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.example.NewsManagement.proto.UserAccountDTO userAccount = 4;</code>
     */
    public com.example.NewsManagement.proto.UserAccountDTO.Builder getUserAccountBuilder() {
      
      onChanged();
      return getUserAccountFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.example.NewsManagement.proto.UserAccountDTO userAccount = 4;</code>
     */
    public com.example.NewsManagement.proto.UserAccountDTOOrBuilder getUserAccountOrBuilder() {
      if (userAccountBuilder_ != null) {
        return userAccountBuilder_.getMessageOrBuilder();
      } else {
        return userAccount_ == null ?
            com.example.NewsManagement.proto.UserAccountDTO.getDefaultInstance() : userAccount_;
      }
    }
    /**
     * <code>.com.example.NewsManagement.proto.UserAccountDTO userAccount = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.NewsManagement.proto.UserAccountDTO, com.example.NewsManagement.proto.UserAccountDTO.Builder, com.example.NewsManagement.proto.UserAccountDTOOrBuilder> 
        getUserAccountFieldBuilder() {
      if (userAccountBuilder_ == null) {
        userAccountBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.NewsManagement.proto.UserAccountDTO, com.example.NewsManagement.proto.UserAccountDTO.Builder, com.example.NewsManagement.proto.UserAccountDTOOrBuilder>(
                getUserAccount(),
                getParentForChildren(),
                isClean());
        userAccount_ = null;
      }
      return userAccountBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.NewsManagement.proto.NewsDTO)
  }

  // @@protoc_insertion_point(class_scope:com.example.NewsManagement.proto.NewsDTO)
  private static final com.example.NewsManagement.proto.NewsDTO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.NewsManagement.proto.NewsDTO();
  }

  public static com.example.NewsManagement.proto.NewsDTO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NewsDTO>
      PARSER = new com.google.protobuf.AbstractParser<NewsDTO>() {
    @java.lang.Override
    public NewsDTO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NewsDTO(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NewsDTO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NewsDTO> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.NewsManagement.proto.NewsDTO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

