// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NewsManagementProto.proto

package com.example.NewsManagement.proto;

public final class NewsManagementProto {
  private NewsManagementProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_NewsManagement_proto_CommentDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_NewsManagement_proto_CommentDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_NewsManagement_proto_NewsDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_NewsManagement_proto_NewsDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_NewsManagement_proto_UserAccountDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_NewsManagement_proto_UserAccountDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_NewsManagement_proto_RoleDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_NewsManagement_proto_RoleDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031NewsManagementProto.proto\022 com.example" +
      ".NewsManagement.proto\"\246\001\n\nCommentDTO\022\n\n\002" +
      "id\030\001 \001(\003\022\014\n\004text\030\002 \001(\t\022E\n\013userAccount\030\003 " +
      "\001(\01320.com.example.NewsManagement.proto.U" +
      "serAccountDTO\0227\n\004news\030\004 \001(\0132).com.exampl" +
      "e.NewsManagement.proto.NewsDTO\"\200\001\n\007NewsD" +
      "TO\022\n\n\002id\030\001 \001(\003\022\020\n\010username\030\002 \001(\t\022\020\n\010pass" +
      "word\030\003 \001(\t\022E\n\013userAccount\030\004 \001(\01320.com.ex" +
      "ample.NewsManagement.proto.UserAccountDT" +
      "O\"z\n\016UserAccountDTO\022\n\n\002id\030\001 \001(\003\022\020\n\010usern" +
      "ame\030\002 \001(\t\022\020\n\010password\030\003 \001(\t\0228\n\005roles\030\004 \001" +
      "(\0132).com.example.NewsManagement.proto.Ro" +
      "leDTO\"#\n\007RoleDTO\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001" +
      "(\tB\027B\023NewsManagementProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_NewsManagement_proto_CommentDTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_NewsManagement_proto_CommentDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_NewsManagement_proto_CommentDTO_descriptor,
        new java.lang.String[] { "Id", "Text", "UserAccount", "News", });
    internal_static_com_example_NewsManagement_proto_NewsDTO_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_NewsManagement_proto_NewsDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_NewsManagement_proto_NewsDTO_descriptor,
        new java.lang.String[] { "Id", "Username", "Password", "UserAccount", });
    internal_static_com_example_NewsManagement_proto_UserAccountDTO_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_example_NewsManagement_proto_UserAccountDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_NewsManagement_proto_UserAccountDTO_descriptor,
        new java.lang.String[] { "Id", "Username", "Password", "Roles", });
    internal_static_com_example_NewsManagement_proto_RoleDTO_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_example_NewsManagement_proto_RoleDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_NewsManagement_proto_RoleDTO_descriptor,
        new java.lang.String[] { "Id", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
