// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NewsManagementProto.proto

package com.example.NewsManagement.proto;

/**
 * Protobuf type {@code com.example.NewsManagement.proto.UserAccountDTO}
 */
public final class UserAccountDTO extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.NewsManagement.proto.UserAccountDTO)
    UserAccountDTOOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserAccountDTO.newBuilder() to construct.
  private UserAccountDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserAccountDTO() {
    username_ = "";
    password_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UserAccountDTO();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UserAccountDTO(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            username_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            password_ = s;
            break;
          }
          case 34: {
            com.example.NewsManagement.proto.RoleDTO.Builder subBuilder = null;
            if (roles_ != null) {
              subBuilder = roles_.toBuilder();
            }
            roles_ = input.readMessage(com.example.NewsManagement.proto.RoleDTO.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(roles_);
              roles_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.NewsManagement.proto.NewsManagementProto.internal_static_com_example_NewsManagement_proto_UserAccountDTO_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.NewsManagement.proto.NewsManagementProto.internal_static_com_example_NewsManagement_proto_UserAccountDTO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.NewsManagement.proto.UserAccountDTO.class, com.example.NewsManagement.proto.UserAccountDTO.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int USERNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object username_;
  /**
   * <code>string username = 2;</code>
   * @return The username.
   */
  @java.lang.Override
  public java.lang.String getUsername() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      username_ = s;
      return s;
    }
  }
  /**
   * <code>string username = 2;</code>
   * @return The bytes for username.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      username_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PASSWORD_FIELD_NUMBER = 3;
  private volatile java.lang.Object password_;
  /**
   * <code>string password = 3;</code>
   * @return The password.
   */
  @java.lang.Override
  public java.lang.String getPassword() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      password_ = s;
      return s;
    }
  }
  /**
   * <code>string password = 3;</code>
   * @return The bytes for password.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPasswordBytes() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      password_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROLES_FIELD_NUMBER = 4;
  private com.example.NewsManagement.proto.RoleDTO roles_;
  /**
   * <code>.com.example.NewsManagement.proto.RoleDTO roles = 4;</code>
   * @return Whether the roles field is set.
   */
  @java.lang.Override
  public boolean hasRoles() {
    return roles_ != null;
  }
  /**
   * <code>.com.example.NewsManagement.proto.RoleDTO roles = 4;</code>
   * @return The roles.
   */
  @java.lang.Override
  public com.example.NewsManagement.proto.RoleDTO getRoles() {
    return roles_ == null ? com.example.NewsManagement.proto.RoleDTO.getDefaultInstance() : roles_;
  }
  /**
   * <code>.com.example.NewsManagement.proto.RoleDTO roles = 4;</code>
   */
  @java.lang.Override
  public com.example.NewsManagement.proto.RoleDTOOrBuilder getRolesOrBuilder() {
    return getRoles();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!getUsernameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, username_);
    }
    if (!getPasswordBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, password_);
    }
    if (roles_ != null) {
      output.writeMessage(4, getRoles());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!getUsernameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, username_);
    }
    if (!getPasswordBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, password_);
    }
    if (roles_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getRoles());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.NewsManagement.proto.UserAccountDTO)) {
      return super.equals(obj);
    }
    com.example.NewsManagement.proto.UserAccountDTO other = (com.example.NewsManagement.proto.UserAccountDTO) obj;

    if (getId()
        != other.getId()) return false;
    if (!getUsername()
        .equals(other.getUsername())) return false;
    if (!getPassword()
        .equals(other.getPassword())) return false;
    if (hasRoles() != other.hasRoles()) return false;
    if (hasRoles()) {
      if (!getRoles()
          .equals(other.getRoles())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUsername().hashCode();
    hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
    hash = (53 * hash) + getPassword().hashCode();
    if (hasRoles()) {
      hash = (37 * hash) + ROLES_FIELD_NUMBER;
      hash = (53 * hash) + getRoles().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.NewsManagement.proto.UserAccountDTO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.NewsManagement.proto.UserAccountDTO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.NewsManagement.proto.UserAccountDTO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.NewsManagement.proto.UserAccountDTO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.NewsManagement.proto.UserAccountDTO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.NewsManagement.proto.UserAccountDTO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.NewsManagement.proto.UserAccountDTO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.NewsManagement.proto.UserAccountDTO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.NewsManagement.proto.UserAccountDTO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.NewsManagement.proto.UserAccountDTO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.NewsManagement.proto.UserAccountDTO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.NewsManagement.proto.UserAccountDTO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.NewsManagement.proto.UserAccountDTO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.NewsManagement.proto.UserAccountDTO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.NewsManagement.proto.UserAccountDTO)
      com.example.NewsManagement.proto.UserAccountDTOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.NewsManagement.proto.NewsManagementProto.internal_static_com_example_NewsManagement_proto_UserAccountDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.NewsManagement.proto.NewsManagementProto.internal_static_com_example_NewsManagement_proto_UserAccountDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.NewsManagement.proto.UserAccountDTO.class, com.example.NewsManagement.proto.UserAccountDTO.Builder.class);
    }

    // Construct using com.example.NewsManagement.proto.UserAccountDTO.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      username_ = "";

      password_ = "";

      if (rolesBuilder_ == null) {
        roles_ = null;
      } else {
        roles_ = null;
        rolesBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.NewsManagement.proto.NewsManagementProto.internal_static_com_example_NewsManagement_proto_UserAccountDTO_descriptor;
    }

    @java.lang.Override
    public com.example.NewsManagement.proto.UserAccountDTO getDefaultInstanceForType() {
      return com.example.NewsManagement.proto.UserAccountDTO.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.NewsManagement.proto.UserAccountDTO build() {
      com.example.NewsManagement.proto.UserAccountDTO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.NewsManagement.proto.UserAccountDTO buildPartial() {
      com.example.NewsManagement.proto.UserAccountDTO result = new com.example.NewsManagement.proto.UserAccountDTO(this);
      result.id_ = id_;
      result.username_ = username_;
      result.password_ = password_;
      if (rolesBuilder_ == null) {
        result.roles_ = roles_;
      } else {
        result.roles_ = rolesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.NewsManagement.proto.UserAccountDTO) {
        return mergeFrom((com.example.NewsManagement.proto.UserAccountDTO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.NewsManagement.proto.UserAccountDTO other) {
      if (other == com.example.NewsManagement.proto.UserAccountDTO.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getUsername().isEmpty()) {
        username_ = other.username_;
        onChanged();
      }
      if (!other.getPassword().isEmpty()) {
        password_ = other.password_;
        onChanged();
      }
      if (other.hasRoles()) {
        mergeRoles(other.getRoles());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.NewsManagement.proto.UserAccountDTO parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.NewsManagement.proto.UserAccountDTO) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object username_ = "";
    /**
     * <code>string username = 2;</code>
     * @return The username.
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string username = 2;</code>
     * @return The bytes for username.
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string username = 2;</code>
     * @param value The username to set.
     * @return This builder for chaining.
     */
    public Builder setUsername(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      username_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string username = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsername() {
      
      username_ = getDefaultInstance().getUsername();
      onChanged();
      return this;
    }
    /**
     * <code>string username = 2;</code>
     * @param value The bytes for username to set.
     * @return This builder for chaining.
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      username_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object password_ = "";
    /**
     * <code>string password = 3;</code>
     * @return The password.
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string password = 3;</code>
     * @return The bytes for password.
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string password = 3;</code>
     * @param value The password to set.
     * @return This builder for chaining.
     */
    public Builder setPassword(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      password_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string password = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPassword() {
      
      password_ = getDefaultInstance().getPassword();
      onChanged();
      return this;
    }
    /**
     * <code>string password = 3;</code>
     * @param value The bytes for password to set.
     * @return This builder for chaining.
     */
    public Builder setPasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      password_ = value;
      onChanged();
      return this;
    }

    private com.example.NewsManagement.proto.RoleDTO roles_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.NewsManagement.proto.RoleDTO, com.example.NewsManagement.proto.RoleDTO.Builder, com.example.NewsManagement.proto.RoleDTOOrBuilder> rolesBuilder_;
    /**
     * <code>.com.example.NewsManagement.proto.RoleDTO roles = 4;</code>
     * @return Whether the roles field is set.
     */
    public boolean hasRoles() {
      return rolesBuilder_ != null || roles_ != null;
    }
    /**
     * <code>.com.example.NewsManagement.proto.RoleDTO roles = 4;</code>
     * @return The roles.
     */
    public com.example.NewsManagement.proto.RoleDTO getRoles() {
      if (rolesBuilder_ == null) {
        return roles_ == null ? com.example.NewsManagement.proto.RoleDTO.getDefaultInstance() : roles_;
      } else {
        return rolesBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.example.NewsManagement.proto.RoleDTO roles = 4;</code>
     */
    public Builder setRoles(com.example.NewsManagement.proto.RoleDTO value) {
      if (rolesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        roles_ = value;
        onChanged();
      } else {
        rolesBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.example.NewsManagement.proto.RoleDTO roles = 4;</code>
     */
    public Builder setRoles(
        com.example.NewsManagement.proto.RoleDTO.Builder builderForValue) {
      if (rolesBuilder_ == null) {
        roles_ = builderForValue.build();
        onChanged();
      } else {
        rolesBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.example.NewsManagement.proto.RoleDTO roles = 4;</code>
     */
    public Builder mergeRoles(com.example.NewsManagement.proto.RoleDTO value) {
      if (rolesBuilder_ == null) {
        if (roles_ != null) {
          roles_ =
            com.example.NewsManagement.proto.RoleDTO.newBuilder(roles_).mergeFrom(value).buildPartial();
        } else {
          roles_ = value;
        }
        onChanged();
      } else {
        rolesBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.example.NewsManagement.proto.RoleDTO roles = 4;</code>
     */
    public Builder clearRoles() {
      if (rolesBuilder_ == null) {
        roles_ = null;
        onChanged();
      } else {
        roles_ = null;
        rolesBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.example.NewsManagement.proto.RoleDTO roles = 4;</code>
     */
    public com.example.NewsManagement.proto.RoleDTO.Builder getRolesBuilder() {
      
      onChanged();
      return getRolesFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.example.NewsManagement.proto.RoleDTO roles = 4;</code>
     */
    public com.example.NewsManagement.proto.RoleDTOOrBuilder getRolesOrBuilder() {
      if (rolesBuilder_ != null) {
        return rolesBuilder_.getMessageOrBuilder();
      } else {
        return roles_ == null ?
            com.example.NewsManagement.proto.RoleDTO.getDefaultInstance() : roles_;
      }
    }
    /**
     * <code>.com.example.NewsManagement.proto.RoleDTO roles = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.NewsManagement.proto.RoleDTO, com.example.NewsManagement.proto.RoleDTO.Builder, com.example.NewsManagement.proto.RoleDTOOrBuilder> 
        getRolesFieldBuilder() {
      if (rolesBuilder_ == null) {
        rolesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.NewsManagement.proto.RoleDTO, com.example.NewsManagement.proto.RoleDTO.Builder, com.example.NewsManagement.proto.RoleDTOOrBuilder>(
                getRoles(),
                getParentForChildren(),
                isClean());
        roles_ = null;
      }
      return rolesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.NewsManagement.proto.UserAccountDTO)
  }

  // @@protoc_insertion_point(class_scope:com.example.NewsManagement.proto.UserAccountDTO)
  private static final com.example.NewsManagement.proto.UserAccountDTO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.NewsManagement.proto.UserAccountDTO();
  }

  public static com.example.NewsManagement.proto.UserAccountDTO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserAccountDTO>
      PARSER = new com.google.protobuf.AbstractParser<UserAccountDTO>() {
    @java.lang.Override
    public UserAccountDTO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UserAccountDTO(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UserAccountDTO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserAccountDTO> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.NewsManagement.proto.UserAccountDTO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

