services:
  postgres:
    image: postgres
    ports:
      - "54320:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=NewsDB
      - POSTGRES_PASSWORD=123
  app:
    image: bigpotato/news-management
    environment:
      - PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/NewsDB
    ports:
      - 8080:8080
    depends_on:
      - postgres
    links:
      - postgres